# Generated by Django 3.0.3 on 2021-04-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_automate_text_datecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automate_text',
            name='number',
            field=models.IntegerField(),
        ),
    ]
