# Generated by Django 3.0.3 on 2021-04-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_auto_20210405_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automate_text',
            old_name='message_to_send',
            new_name='message',
        ),
    ]
